apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
data:
  DB_USER: {{ .Values.dbconfig.DB_USER }}
  DB_HOST: {{ .Values.dbconfig.DB_HOST }}
  DB_DATABASE: {{ .Values.dbconfig.DB_DATABASE }}
  DB_PORT: {{ .Values.dbconfig.DB_PORT }}